Feature/welcome screen
OskarBiwejnis/WeatherApp pull request #1
Opened 2023-07-11 12:53 UTC by OskarBiwejnis

Project setup and first VC

2023-07-11 14:07 UTC, erykmroczko requested changes

2023-07-11 14:07 UTC, erykmroczko commented on WeatherApp/WelcomeVC.swift
> +class WelcomeVC: UIViewController {
nazywajmy to pełnym zdaniem: WelcomeViewController

2023-07-11 14:07 UTC, erykmroczko commented on WeatherApp/WelcomeVC.swift
> +    private let icon: UIImageView = {
Mamy zatem i widok i logikę aplikacji w jednej klasie... przydałoby się to jakoś rozdzielić. Spróbuj zrobić klasę WelcomeView, której zadaniem będzie zdefiniowanie widoków i ogólnego UI modułu welcome

2023-07-12 08:02 UTC, erykmroczko requested changes

2023-07-12 08:02 UTC, erykmroczko commented on WeatherApp/WelcomeView.swift
> +    private let label: UILabel = {
Przydałoby się lepiej nazwać teraz te buttony, labelki itd. Np. proceedButton

2023-07-12 08:35 UTC, andrzejplatek requested changes

2023-07-12 08:35 UTC, andrzejplatek commented on WeatherApp/WelcomeViewController.swift
> +
tutaj za dużo spacji, wystarczy 1

2023-07-12 08:35 UTC, andrzejplatek commented on WeatherApp/WelcomeViewController.swift
> +    }
Poczytaj sobie o cyklu życia viewControllera i kolejnych funkcjach które się wykonują podczas jego odpalania. Generalnie nadpisywanie widoku powinno być w innej funkcji. Poza tym powinieneś też mieć referencję do widoku, żeby móc się z poziomu VC odwoływać do widoku. Tak więc musisz zrobić oddzielną zmienną która będzie zawierać widok i nadpisywać nią widok.

2023-07-12 08:35 UTC, andrzejplatek commented on WeatherApp/WelcomeView.swift
> +        proceedButton.layer.cornerRadius = 20
pamiętaj żeby stałe wydzielić do enuma Constants

2023-07-12 09:35 UTC, andrzejplatek requested changes

2023-07-12 09:35 UTC, andrzejplatek commented on WeatherApp/WelcomeViewController.swift
> +        view = welcomeView
super, o to chodziło!

2023-07-12 09:35 UTC, andrzejplatek commented on WeatherApp/WelcomeView.swift
> +        setup()
tutaj nie musisz dawać funkcji setup, wystarczy że zostawisz to co zostało wygenerowane

2023-07-12 09:35 UTC, andrzejplatek commented on WeatherApp/WelcomeView.swift
> +    }
tego w ogóle nie musisz pisać

2023-07-12 10:37 UTC, andrzejplatek requested changes

2023-07-12 10:37 UTC, andrzejplatek commented on WeatherApp/WelcomeView.swift
> +        static let titleLabelYOffset = -50
w tych Constants nie dajemy minusów, już w samych constraintach je umieszcamy

2023-07-12 10:37 UTC, andrzejplatek commented on WeatherApp/WelcomeView.swift
> +            make.centerX.equalTo(self.layoutMarginsGuide)
możesz zrobić po prostu equalToSuperview

2023-07-12 10:37 UTC, andrzejplatek commented on WeatherApp/WelcomeView.swift
> +        static let iconImageViewToTitleLabelDistance = -10
postaraj się zwięźlej pisać te nazwy, np. imageBottomMargin lub coś w tym stylu

2023-07-12 10:37 UTC, andrzejplatek commented on WeatherApp/WelcomeView.swift
> +        static let proceedButtonHeight = 50
zamiast robić width i height zrób CGSize (proceedButtonSize)

2023-07-12 10:37 UTC, andrzejplatek commented on WeatherApp/WelcomeView.swift
> +        static let iconImageViewCornerRadius = 40
podobnie użyj bardziej zwięzłej nazwy- np. imageCornerRadius

2023-07-12 10:37 UTC, andrzejplatek commented on WeatherApp/WelcomeView.swift
> +            make.width.height.equalTo(Constants.iconImageSize)
pisząc constrainty staramy się to robić w taki sposób żeby było wiadomo co i w jakiej kolejności jest widoczne na ekranie. Tak więc elementy na górze ekranu powinny być deklarowane jako pierwsze, a na dole ekranu jako ostatnie. Oprócz tego postaraj się używać relacji pomiędzy elementami zamiast zmieniać offset od środka ekranu. Jeden element który chcesz żeby był na środku oczywiście możesz umieścić, ale reszta powinna mieć już relacje w stosunku do niego

2023-07-12 10:37 UTC, andrzejplatek commented on WeatherApp/SceneDelegate.swift
> +        window?.rootViewController = nav
nie używamy takich skróconych nazw, tylko pełne, tak więc tu będzie navigationController

2023-07-12 10:37 UTC, andrzejplatek commented on WeatherApp/SceneDelegate.swift
>          // This delegate does not imply the connecting scene or session are new (see `application:configurationForConnectingSceneSession` instead).
Wywal te komentarze

2023-07-12 11:30 UTC, merged