Coordinators
OskarBiwejnis/WeatherApp pull request #17
Opened 2023-09-19 07:02 UTC by OskarBiwejnis

2023-09-19 07:17 UTC, andrzejplatek requested changes

2023-09-19 07:17 UTC, andrzejplatek commented on WeatherApp/Helpers/Coordinator.swift
> +}
Nie do końca, generalnie na każdy moduł powinniśmy mieć oddzielny koordynator. App coordinator powinien odpowiadać za wywołanie pierwszego koordynatora modułu który będzie się pojawiać. Tak więc w tym protokole nie powinno być takich funkcji jak goToWelcomeScreen itp. Tylko sama funkcja start. Co ciekawe my nawet nie korzystamy z protokołu, tylko z bazowej klasy BaseCoordinator po której dziedziczymy.

2023-09-19 07:17 UTC, andrzejplatek commented on WeatherApp/Modules/Forecast/ForecastViewModel.swift
> +    weak var appCoordinator: Coordinator?
Ani w VC ani w VM nie powinno być referencji do Koordynatora. To Koordynator tworzy VM i przekazuje go jako argument inita ViewControllera. Nie musisz nawet trzymać referencji do VC, bo jest ona trzymana w NavigationControllerze.

2023-09-19 07:17 UTC, andrzejplatek commented on WeatherApp/Modules/Search/SearchViewController.swift
> +                self?.searchViewModel.appCoordinator?.goToForecastScreen(city: city)
w celu nawigacji powinieneś mieć w VM publisher który będzie publikować eventy nawigacyjne i do niego się podpina Koordynator. Generalnie to my załatwiamy to w taki sposób, że mamy dodatkowy protokół do którego konformuje VM, który służy do komunikacji Koordynator <-> VM, w nim jest zawarty ten publisher eventów i ewentualnie jakieś inne rzeczy które mogą być potrzebne

2023-09-20 11:42 UTC, andrzejplatek requested changes

2023-09-20 11:42 UTC, andrzejplatek commented on WeatherApp/Supporting Files/SearchCoordinator.swift
> +import Combine
każdy koordynator wsadzasz do nowego folderu który nazwywamy `Coordinator` w danym module

2023-09-20 11:42 UTC, andrzejplatek commented on WeatherApp/Helpers/Navigable.swift
> +}
Podobnie jak masz ViewModelContract, tak też powinieneś mieć ViewModelCoordinatorContract- dla każdego modułu powinien być oddzielny

2023-09-20 11:42 UTC, andrzejplatek commented on WeatherApp/Helpers/BaseCoordinator.swift
> +    }
ParentCoordinator nie jest potrzebny, tylko navigationController. I też w inicie nie zawsze chcemy przekazywać navigationController, np. w momencie gdy chcemy zembedować jeden ekran w drugi, ale jak na ten projekt może tak zostać

2023-09-20 11:42 UTC, andrzejplatek commented on WeatherApp/Helpers/NavigationEvent.swift
> +}
To powinno być też oddzielne dla każdego modułu

2023-09-20 11:42 UTC, andrzejplatek commented on WeatherApp/Supporting Files/SearchCoordinator.swift
> +        navigationController.pushViewController(searchViewController, animated: true)
każdy koordynator powinien mieć funkcję start, w której faktycznie dokonuje się nawigacja zamiast w inicie. Możesz sobie napisać funkcję pomocniczą na baseKoordynatorze np. coordinate(_ to: BaseCoorinator), która będzie jednocześnie zapisywać w dzieciach dany koordynator oraz go startować

2023-09-21 09:09 UTC, isokal requested changes

2023-09-21 09:09 UTC, isokal commented on WeatherApp/Helpers/Navigable.swift
> +}
mozesz usunac bo nie używasz

2023-09-21 09:09 UTC, isokal commented on WeatherApp/Helpers/NavigationEvent.swift
> +}
już nie używasz tej klasy, usuń

2023-09-21 09:09 UTC, isokal commented on WeatherApp/Modules/Welcome/WelcomeViewModel.swift
> +}
pozmieniaj te nazwy na lepsze, teraz są takie same jak te w EventInput co jest mocno mylące. np openSearch, openForecast

2023-09-21 11:54 UTC, isokal approved these changes

2023-09-22 13:36 UTC, merged