Swinject
OskarBiwejnis/WeatherApp pull request #18
Opened 2023-09-25 11:03 UTC by OskarBiwejnis

2023-09-25 14:52 UTC, abrodowski requested changes

2023-09-25 14:52 UTC, abrodowski commented on WeatherApp/Modules/Forecast/Coordinator/ForecastCoordinator.swift
> +        let forecastViewController = Assembler.shared.resolver.resolve(ForecastViewController.self, argument: city)!
- Raczej unikamy force unwrap, my generalnie korzystamy tu z pomocniczej funkcji `Assembler.shared.resolver.resolve(ForecastViewController.self, argument: city).forceResolve(),`

- zamiast podawać argument w ten sposób zrób struct ModuleInput {} i wtedy `.resolve(ForecastViewController.self, argument: moduleInput`, bardzo to upraszcza w sytuacji gdy potrzebujesz użyć wielu argumentów

2023-09-27 07:24 UTC, andrzejplatek requested changes

2023-09-27 07:24 UTC, andrzejplatek commented on WeatherApp/Modules/Search/Coordinator/SearchCoordinator.swift
> +        self.searchViewModel = searchViewModel
w sumie nie musisz tutaj robić dodatkowej zmiennej searchViewModel, wystarczy że przekażesz ją jako argument w funkcji bindActions. Oprócz tego zauważ że resolvujesz tutaj viewModel, który już został zresolvowany w viewControllerze. Tak więc żeby się dostać do VM wystarczy że zrobisz searchViewController.viewModel (tylko musisz usunąć private)

2023-09-27 07:24 UTC, andrzejplatek commented on WeatherApp/Modules/Search/Coordinator/SearchCoordinator.swift
> +                                                      moduleInput: ForecastViewModel.ModuleInput(city: city))
koordynatory też powinny być resolvowane

2023-09-27 08:58 UTC, andrzejplatek commented on WeatherApp/Modules/Search/SearchViewModel.swift
> +class SearchViewModel: SearchViewModelContract {
To było git, to znaczy powinny być dwa różne protokoły i do tych dwóch protokołów powinien konformować SearchViewModel. W momencie gdy chcesz przekazywać viewModel w koordynatorze, to musisz zrobić casta na SearchViewModelCoordinatorContract

2023-09-27 09:24 UTC, andrzejplatek approved these changes

2023-09-27 09:44 UTC, merged