New file structure and corrections
OskarBiwejnis/WeatherApp pull request #9
Opened 2023-07-18 12:03 UTC by OskarBiwejnis

2023-07-18 13:26 UTC, andrzejplatek requested changes

2023-07-18 16:31 UTC, isokal requested changes
poza tym sam search nie do końca dobrze działa - wiecej info na kanale na placku

2023-07-18 16:31 UTC, isokal commented on WeatherApp/Modules/Search/SearchViewModel.swift
>          }
to nie do końca dobrze dziala, chcemy żeby zachowywało się to tak jak np w searchu Google, czyli
1. czekamy 1.1 sekundy aż nie będzie żadnych zmian w wartości w search barze (dla lepszego user experience timeInterval powinien być niższy, spróbuj użyć 0.35s)
2. bierzemy wartość z searchbara i wykonujemy request `fetchCities`
3. po udanym `fetchCities` wyświetlamy wyniki

2023-07-19 09:22 UTC, isokal approved these changes

2023-07-19 10:16 UTC, merged